---
- name: Install Zabbix Agent
  hosts: zabbix_agents
  tasks:
    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: latest  
      become: yes
      tags:
        - zabbix-agent

- name: Install Zabbix Server
  hosts: zabbix_server
  tasks:
    - name: Install PostgreSQL and required packages
      apt:
        name: 
          - zabbix-server-pgsql  # Пакет Zabbix Server
          - postgresql            # Пакет PostgreSQL
          - postgresql-contrib    # Пакет дополнений PostgreSQL
          - postgresql-libs       # Пакет библиотек PostgreSQL
          - zabbix-pgsql          # Драйвер PostgreSQL для Zabbix
        state: latest
      become: yes
      tags:
        - zabbix-server
