---
- name: Install Zabbix Agent
  hosts: zabbix_agents
  tasks:
    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: latest  
      become: yes
      tags:
        - zabbix-agent

