---
- name: Install and configure Filebeat
  hosts: web-server1, web-server2
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Filebeat Docker image
      docker_image:
        name: docker.elastic.co/beats/filebeat:7.17.13

    - name: Configure Filebeat
      docker_container:
        name: filebeat
        image: docker.elastic.co/beats/filebeat:7.17.13
        state: started
        restart_policy: always
        volumes:
          - /var/log/nginx:/var/log/nginx:ro
          - /etc/filebeat/filebeat.yml:/etc/filebeat/filebeat.yml
        command: "filebeat -e"
      notify:
        - restart filebeat
      environment:
        - output.elasticsearch.hosts=["{{ hostvars['elasticsearch']['ansible_default_ipv4']['address'] }}:9200"]

  handlers:
    - name: restart filebeat
      service:
        name: filebeat
        state: restarted

- name: Restart Filebeat container
  hosts: web-server1, web-server2
  tasks:
    - name: Restart Filebeat container
      docker_container:
        name: filebeat
        state: restarted
