---
- name: Install and configure Elasticsearch
  hosts: elasticsearch
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Elasticsearch Docker image
      docker_image:
        name: docker.elastic.co/elasticsearch/elasticsearch:7.17.13

    - name: Run Elasticsearch container
      docker_container:
        name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
        state: started
        restart_policy: always
