---
- name: Install and configure Nginx
  hosts: web-server1, web-server2
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Change default page on web-server1
      replace:
        path: /var/www/html/index.html
        regexp: 'Welcome to nginx'
        replace: 'WEBSERVER1'
      when: "'web-server1' in inventory_hostname"

    - name: Change default page on web-server2
      replace:
        path: /var/www/html/index.html
        regexp: 'Welcome to nginx'
        replace: 'WEBSERVER2'
      when: "'web-server2' in inventory_hostname"

    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
